version: '3.9'
services:
    postgres:
        image: postgres
        hostname: postgres
        ports:
            - 3001:5432
        env_file:
            - src/main/resources/.env
        networks:
            - forum_network

    api:
        build: .
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
            - src/main/resources/.env
        networks:
            - forum_network

networks:
    forum_network:
        driver: bridge