version: '3.1'
services:
    api:
        build: .
        ports:
            - 3000:3000
        network_mode: "host"
        depends_on:
            - postgres
        env_file:
            - src/main/resources/.env

    postgres:
        image: postgres
        ports:
            - 3001:5432
        env_file:
            - src/main/resources/.env
