server:
    port: 3000
.env:
    directory: "."
    prefix: ""
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?ssl=${POSTGRES_SSL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        properties:
            hibernate:
                ddl-auto: create-drop
                show_sql: true
                format_sql: true
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
    h2:
        console:
            enabled: true
jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}